---
deployment:
  tasks:
    - export COMPOSER_ALLOW_SUPERUSER=1
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
      - cp -r app ../public_html/
      - cp -r bootstrap ../public_html/
      - cp -r config ../public_html/
      - cp -r database ../public_html/
      - cp -r public ../public_html/
      - cp -r resources ../public_html/
      - cp -r routes ../public_html/
      - cp -r storage ../public_html/
      - cp -r vendor ../public_html/
      - cp artisan ../public_html/
      - cp composer.json ../public_html/
      - cp composer.lock ../public_html/
      - cp index.php ../public_html/
      - cp .env.example ../public_html/
      - cp .htaccess ../public_html/